### ISSUE TITLE
Rico does not list Air Balloon Alolan Golem

### ISSUE THREAD

**Issue by Fiore1300** [adrianywh/adrianywh.github.io#2]
Fighting Rico today while using this app, and I was surprised that Alolan Golem was immune to my High Horsepower. The guide as it stands only lists a Quick Claw variant. Or perhaps the item is merely wrong?

**Comment by adrianywh** [comment]
May I know which version of Pokemon you were playing so I can look into it?

**Comment by Fiore1300** [comment]
Ultra Sun was the version I was playing.

**Comment by adrianywh** [comment]
noted. I will look into it

**Comment by adrianywh** [comment]
Fixed in version 

turns out i was using the pkmn and trainer list from sun/moon version. Thanks

9859d2e722316b3121219f3f69fcda05c3e6f6f3
